name: CI BLAS

on:
  push:
    branches: [ "main" ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v4
      
      - name: Install dependencies
        run: sudo apt-get update && sudo apt-get install -y libopenblas-dev
        
      - name: Build
        run: make
        
      - name: Run tests
        run: ./myblas